[project]
name = "racketcon-2025"
version = "0.1.0"
description = "RacketCon 2025 experiments and tools"
readme = "README.org"
requires-python = ">=3.13"
dependencies = [
    "yt-dlp>=2025.9.26",
]

[tool.uv]
dev-dependencies = []
